### ISSUE TITLE
Fallback to Mix.env

### ISSUE THREAD

**Issue by teamon** [getsentry/raven-elixir#42]
https://github.com/getsentry/raven-elixir/blob/master/lib/sentry/event.ex#L63

It causes 

```
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.binary_to_existing_atom(nil, :utf8)
        (sentry) lib/sentry/event.ex:63: Sentry.Event.transform_exception/2
        (sentry) lib/sentry.ex:59: Sentry.capture_exception/2
```

because `MIX_ENV` is not set.

I think it could fallback to `Mix.env`.

**Comment by jeregrine** [comment]
@teamon We can provide a better error message but this is expected behavior.

**Comment by mitchellhenke** [comment]
created https://github.com/getsentry/raven-elixir/issues/45

**Comment by teamon** [comment]
@jeregrine Can you elaborate a bit more? I'm curious why check MIX_ENV but skip Mix.env

**Comment by jeregrine** [comment]
@teamon mix might not be available. Say if you use it with a release. Its not good practice to rely on Mix.env.

**Comment by teamon** [comment]
Right, makes sense. Thanks :)
